package ventanas.Cubico;

import controladores.Coordinador;
import java.awt.Dimension;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import ventanas.ven_Principal;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maryonday
 */
public class VentanaCubico extends javax.swing.JFrame {
    private Coordinador miCoordinador;
    private int nun_cubico; 
    private Dimension tamPantalla;
    private Rectangle pantalla;
     public VentanaCubico(ven_Principal miVentana, boolean b) {
          initComponents();
          
        float an = 0.68F; // una ventana al 50% del tamaño de la pantalla
        float escalar = 0.9F;
        int ancho = (int)(Toolkit.getDefaultToolkit().getScreenSize(). width*an);
        int alto = (int)(Toolkit.getDefaultToolkit().getScreenSize(). height*escalar);
        this.setSize(ancho,alto);
        
        setLocationRelativeTo(null);
        setResizable(false);  
        
        addWindowListener(new WindowAdapter(){
        	
        @Override
        public void windowClosing(WindowEvent e){
        	Object[] options = {"Si","No"};
        	int n = JOptionPane.showOptionDialog( null,
        		"¿Seguro que Desea Cerrar?","Confirmacion",JOptionPane.YES_NO_CANCEL_OPTION,
        	   JOptionPane.WARNING_MESSAGE,null,options,options[0]);
        	 if (n == JOptionPane.YES_OPTION){
                     setVisible(false);
                     miCoordinador.miVentanaCubico.setVisible(true);
                 }
        	 else if( n == JOptionPane.NO_OPTION){ }
        	
        }
        
        });
         
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        lb_hora = new javax.swing.JLabel();
        lb_horaSALIDAD = new javax.swing.JLabel();
        lt_num_Cubiculo = new javax.swing.JLabel();
        lb_entrada = new javax.swing.JLabel();
        lb_salida = new javax.swing.JLabel();
        Lb_titulo1 = new javax.swing.JLabel();
        lb_H_extra_entrada = new javax.swing.JLabel();
        lb_H_extra_salidad = new javax.swing.JLabel();
        tx_horaExtra = new javax.swing.JTextField();
        tx_horaSALIDAD_extra = new javax.swing.JTextField();
        Lb_titulo2 = new javax.swing.JLabel();
        Lb_titulo = new javax.swing.JLabel();
        lt_fecha = new javax.swing.JLabel();
        jp_lineamineto = new javax.swing.JPanel();
        cb_1 = new javax.swing.JCheckBox();
        cb_2 = new javax.swing.JCheckBox();
        cb_3 = new javax.swing.JCheckBox();
        cb_4 = new javax.swing.JCheckBox();
        cb_8 = new javax.swing.JCheckBox();
        cb_7 = new javax.swing.JCheckBox();
        cb_6 = new javax.swing.JCheckBox();
        cb_5 = new javax.swing.JCheckBox();
        cb_12 = new javax.swing.JCheckBox();
        cb_11 = new javax.swing.JCheckBox();
        cb_10 = new javax.swing.JCheckBox();
        cb_9 = new javax.swing.JCheckBox();
        lt_fecha1 = new javax.swing.JLabel();
        bt_SeleccionarTodo = new java.awt.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_Cubico = new javax.swing.JTable();
        bt_Aceptar = new javax.swing.JButton();
        bt_cancelar = new javax.swing.JButton();
        Lb_titulo3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jt_NomRep = new javax.swing.JFormattedTextField();
        jt_idRepres = new javax.swing.JFormattedTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jLayeredPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_hora.setFont(new java.awt.Font("Ubuntu", 2, 18)); // NOI18N
        lb_hora.setForeground(new java.awt.Color(39, 127, 228));
        lb_hora.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_hora.setText(" entrada");
        lb_hora.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 185, 0)));
        lb_hora.setEnabled(false);
        jPanel1.add(lb_hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 11, 110, 30));

        lb_horaSALIDAD.setFont(new java.awt.Font("Ubuntu", 2, 18)); // NOI18N
        lb_horaSALIDAD.setForeground(new java.awt.Color(39, 127, 228));
        lb_horaSALIDAD.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_horaSALIDAD.setText("salidad");
        lb_horaSALIDAD.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 185, 0)));
        lb_horaSALIDAD.setEnabled(false);
        jPanel1.add(lb_horaSALIDAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 13, 120, 30));

        lt_num_Cubiculo.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        lt_num_Cubiculo.setText("N°");
        jPanel1.add(lt_num_Cubiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 14, 50, 27));

        lb_entrada.setText("Hora/Entrada ");
        jPanel1.add(lb_entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 13, -1, 31));

        lb_salida.setText("Hora/Salida");
        jPanel1.add(lb_salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 13, -1, 31));

        Lb_titulo1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        Lb_titulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lb_titulo1.setText("Renovación");
        jPanel1.add(Lb_titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 47, -1, 21));

        lb_H_extra_entrada.setText("Hora/Entrada ");
        jPanel1.add(lb_H_extra_entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 74, -1, 40));

        lb_H_extra_salidad.setText("Hora/Salida ");
        jPanel1.add(lb_H_extra_salidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 74, -1, 40));

        tx_horaExtra.setColumns(1);
        tx_horaExtra.setFont(new java.awt.Font("Cantarell", 2, 18)); // NOI18N
        tx_horaExtra.setForeground(new java.awt.Color(39, 127, 228));
        jPanel1.add(tx_horaExtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 75, 106, 40));

        tx_horaSALIDAD_extra.setColumns(1);
        tx_horaSALIDAD_extra.setFont(new java.awt.Font("Cantarell", 2, 18)); // NOI18N
        tx_horaSALIDAD_extra.setForeground(new java.awt.Color(39, 127, 228));
        jPanel1.add(tx_horaSALIDAD_extra, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 120, 40));

        Lb_titulo2.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        Lb_titulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lb_titulo2.setText("LINEAMIENTO DE USO Y SEGURIDAD (LEER Y SELECCIONAR )");

        Lb_titulo.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        Lb_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lb_titulo.setText("CARTA DE COMPROMISO PARA USO DE CUBÍCULOS");

        lt_fecha.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        lt_fecha.setText("fecha");

        jp_lineamineto.setBackground(new java.awt.Color(226, 226, 226));
        jp_lineamineto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jp_lineamineto.setLayout(null);

        cb_1.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        cb_1.setText("1.  No Extraviar las llaves.");
        jp_lineamineto.add(cb_1);
        cb_1.setBounds(70, 40, 710, 23);

        cb_2.setBackground(new java.awt.Color(1, 1, 1));
        cb_2.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        cb_2.setForeground(new java.awt.Color(254, 254, 254));
        cb_2.setText("2.  Respetar el tiempo de uso (2 horas)");
        jp_lineamineto.add(cb_2);
        cb_2.setBounds(70, 60, 710, 23);

        cb_3.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        cb_3.setText("3.  Realiza trabajos y/o estudiar en grupo. No elaboraremos maquetas ni similares.");
        jp_lineamineto.add(cb_3);
        cb_3.setBounds(70, 80, 710, 23);

        cb_4.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        cb_4.setText("4.  No utilizar: exactos, pilotos, gomas,hielo seco, carton, masilla, pintura, etc.");
        jp_lineamineto.add(cb_4);
        cb_4.setBounds(70, 100, 710, 23);

        cb_8.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        cb_8.setText("8.  Dejar la mesa y sillas libres de retos de deshechos de borrador, papeles u otros.");
        jp_lineamineto.add(cb_8);
        cb_8.setBounds(70, 180, 710, 23);

        cb_7.setBackground(new java.awt.Color(1, 1, 1));
        cb_7.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        cb_7.setForeground(new java.awt.Color(254, 254, 254));
        cb_7.setText("7.  Evitar la ingesta de alimentos y/o bebidas, incluyendo agua.");
        jp_lineamineto.add(cb_7);
        cb_7.setBounds(70, 160, 710, 23);

        cb_6.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        cb_6.setText("6.  Llegar puntualmente a la hora de la reservacion o maximo 15 minutos despues.");
        jp_lineamineto.add(cb_6);
        cb_6.setBounds(70, 140, 710, 23);

        cb_5.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        cb_5.setText("5.  Mantener un comportamiento ejemplar: voz, baja, uso de audífonos.");
        jp_lineamineto.add(cb_5);
        cb_5.setBounds(70, 120, 710, 23);

        cb_12.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        cb_12.setText("12. Reportar cualquier incidencia que de presente al entrar o al salir.");
        jp_lineamineto.add(cb_12);
        cb_12.setBounds(70, 260, 710, 23);

        cb_11.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        cb_11.setText("11. Cerrar y devolver la llave");
        jp_lineamineto.add(cb_11);
        cb_11.setBounds(70, 240, 710, 23);

        cb_10.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        cb_10.setText("10. Recoger todas nuestras pertenencias.");
        jp_lineamineto.add(cb_10);
        cb_10.setBounds(70, 220, 710, 23);

        cb_9.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        cb_9.setText("9.  Colocar las sillas en su lugar correspondiente: debajo de la mesa.");
        jp_lineamineto.add(cb_9);
        cb_9.setBounds(70, 200, 710, 23);

        lt_fecha1.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        lt_fecha1.setText("NOS COMPROMETEMOS A ");
        jp_lineamineto.add(lt_fecha1);
        lt_fecha1.setBounds(70, 10, 237, 18);

        bt_SeleccionarTodo.setBackground(new java.awt.Color(66, 178, 222));
        bt_SeleccionarTodo.setLabel("Marcar Todo");
        bt_SeleccionarTodo.setName("Marcar Todo"); // NOI18N
        bt_SeleccionarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_SeleccionarTodoActionPerformed(evt);
            }
        });
        jp_lineamineto.add(bt_SeleccionarTodo);
        bt_SeleccionarTodo.setBounds(10, 290, 90, 23);

        jt_Cubico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Cedula", "Nombre", "*Carrera"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jt_Cubico.setColumnSelectionAllowed(true);
        jt_Cubico.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jt_Cubico);
        jt_Cubico.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        if (jt_Cubico.getColumnModel().getColumnCount() > 0) {
            jt_Cubico.getColumnModel().getColumn(0).setResizable(false);
            jt_Cubico.getColumnModel().getColumn(1).setResizable(false);
            jt_Cubico.getColumnModel().getColumn(2).setResizable(false);
        }

        bt_Aceptar.setBackground(new java.awt.Color(121, 224, 231));
        bt_Aceptar.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        bt_Aceptar.setForeground(new java.awt.Color(0, 185, 6));
        bt_Aceptar.setText("ACEPTAR");
        bt_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_AceptarActionPerformed(evt);
            }
        });

        bt_cancelar.setBackground(new java.awt.Color(121, 224, 231));
        bt_cancelar.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        bt_cancelar.setForeground(new java.awt.Color(0, 185, 6));
        bt_cancelar.setText("CANCELAR");
        bt_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelarActionPerformed(evt);
            }
        });

        Lb_titulo3.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        Lb_titulo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lb_titulo3.setText("DATOS DEL USUARIO ");

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jTextField1.setText("  estudiante, profesor, administrativo (seleccionar) con ");
        jTextField1.setBorder(null);

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jTextField3.setText("credenciales (N° cédula/pasaporte)");
        jTextField3.setBorder(null);

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jTextField4.setText("Yo");
        jTextField4.setBorder(null);

        jt_NomRep.setBackground(new java.awt.Color(253, 251, 251));
        jt_NomRep.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jt_NomRep.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N

        jt_idRepres.setBackground(new java.awt.Color(253, 251, 251));
        jt_idRepres.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jt_idRepres.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jTextField2.setText("Nos comprometemos a través del presente documento a cumplir fielmente con lo establecido en el reglamento de CRAI,");
        jTextField2.setBorder(null);

        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jTextField6.setText("en representación de mi equipo, quienes debajo escribirán sus credenciales. ");
        jTextField6.setBorder(null);

        jTextField7.setEditable(false);
        jTextField7.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jTextField7.setText("sobrel uso de cubículos por el bien de su mantenimiento. ");
        jTextField7.setBorder(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jt_NomRep)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(169, 169, 169))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jt_idRepres, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4)
                    .addComponent(jt_NomRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_idRepres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jTextField5.setText("y nos comprometemos a cumplirlos en su totalidad. *Llenando* el presente documento como usuarios responsable.");
        jTextField5.setBorder(null);

        jTextField8.setEditable(false);
        jTextField8.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jTextField8.setText("Conforme con lo indicado, aceptamos haber léido y comprendido los lineamientos de uso y seguridad de los cubículos,");
        jTextField8.setBorder(null);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jp_lineamineto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(30, 30, 30))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(Lb_titulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(bt_Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(bt_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130))))
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(503, 503, 503)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(Lb_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(lt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(Lb_titulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(Lb_titulo)
                .addGap(10, 10, 10)
                .addComponent(lt_fecha)
                .addGap(3, 3, 3)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(Lb_titulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jp_lineamineto, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Lb_titulo3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jLayeredPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Lb_titulo2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Lb_titulo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lt_fecha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jp_lineamineto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(bt_Aceptar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(bt_cancelar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Lb_titulo3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jTextField5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jTextField8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jSeparator2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane2.setViewportView(jLayeredPane1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelarActionPerformed
        // TODO add your handling code here:
        miCoordinador.CubiculoStatus(0);
        limpiar();
    }//GEN-LAST:event_bt_cancelarActionPerformed

    private void bt_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_AceptarActionPerformed
        // TODO add your handling code here:
        registrar();
    }//GEN-LAST:event_bt_AceptarActionPerformed

    private void bt_SeleccionarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_SeleccionarTodoActionPerformed
        cb_1.setSelected(true);
        cb_2.setSelected(true);
        cb_3.setSelected(true);
        cb_4.setSelected(true);
        cb_5.setSelected(true);
        cb_6.setSelected(true);
        cb_7.setSelected(true);
        cb_8.setSelected(true);
        cb_9.setSelected(true);
        cb_10.setSelected(true);
        cb_11.setSelected(true);
        cb_12.setSelected(true);
    }//GEN-LAST:event_bt_SeleccionarTodoActionPerformed
       public void inico(int cubico){
        DefaultTableModel modelo = (DefaultTableModel) jt_Cubico.getModel();   
        modelo.setNumRows(7);
        // asignamos el el numero de cubico
        nun_cubico= cubico;
        lt_num_Cubiculo.setText("N° "+nun_cubico);
        // asignamos la fecha 
        lt_fecha.setText(miCoordinador.MostrarFechaHora("fecha"));
        // traemos la hora 
        String hora = this.miCoordinador.MostrarFechaHora("hora");
        
        String[] salida= new String[3];
        String estado = hora.substring(9, 11);
        int listo = 0;
        try {
           listo = Integer.parseInt(estado.replace("AM","1"));
        } catch (Exception e) {
            System.out.println("Ya pasamos a la tarde");
        }
        
        // proceso para aumentar las dos horas de uso 
        int Horas;
        salida[0]= hora.substring(0, 2);// horas
        salida[2]= hora.substring(2, 5);// minutos
        Horas = Integer.parseInt(salida[0]); // convertidas en numero
        salida[1] =  Horas >= 9 ? "" + (Horas+2) : "0" + (Horas+2);
         if(listo == 1){
            System.out.println("1---- "+listo);
            if(Horas>=10){
                // pasaremos a la tarde
                 System.out.println("1- estamos en la tarde ");
                lb_hora.setText(salida[0]+""+salida[2]+" AM");
                lb_horaSALIDAD.setText( salida[1]+""+salida[2]+" PM");
            }else{
                // estamos en la manana 
                System.out.println("1- estamos en la manana ");
                int tem= Integer.parseInt(salida[0])-12;
                if(tem < 0){
                     salida[0]= ""+12;
                }
               lb_hora.setText(salida[0]+""+salida[2]+" AM");
               lb_horaSALIDAD.setText( salida[1]+""+salida[2]+" AM");
              
            }
            
        }else{
            System.out.println(" ----"+listo);
            if(Horas>=10){
                // pasaremos a la tarde
                System.out.println(" ___ estamos en la tarde ");
                //salida[2] = hora.substring(2,9);
                int tem= Integer.parseInt(salida[1])-12;
                if(tem == 0){
                     salida[1]= ""+12;
                }else{
                salida[1] = ""+tem;
                }
                lb_hora.setText(salida[0]+""+salida[2]+" PM");
                lb_horaSALIDAD.setText( salida[1]+""+salida[2]+" AM");                
                
              //  System.out.println(tem-12+" "+salida[1]);
            }else{
                // estamos en la manana 
               System.out.println(" ___ estamos en la manana ");
               lb_hora.setText(salida[0]+""+salida[2]+" PM");
               lb_horaSALIDAD.setText( salida[1]+""+salida[2]+" PM");
            }
        }       
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lb_titulo;
    private javax.swing.JLabel Lb_titulo1;
    private javax.swing.JLabel Lb_titulo2;
    private javax.swing.JLabel Lb_titulo3;
    private javax.swing.JButton bt_Aceptar;
    private java.awt.Button bt_SeleccionarTodo;
    private javax.swing.JButton bt_cancelar;
    private javax.swing.JCheckBox cb_1;
    private javax.swing.JCheckBox cb_10;
    private javax.swing.JCheckBox cb_11;
    private javax.swing.JCheckBox cb_12;
    private javax.swing.JCheckBox cb_2;
    private javax.swing.JCheckBox cb_3;
    private javax.swing.JCheckBox cb_4;
    private javax.swing.JCheckBox cb_5;
    private javax.swing.JCheckBox cb_6;
    private javax.swing.JCheckBox cb_7;
    private javax.swing.JCheckBox cb_8;
    private javax.swing.JCheckBox cb_9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JPanel jp_lineamineto;
    private javax.swing.JTable jt_Cubico;
    private javax.swing.JFormattedTextField jt_NomRep;
    private javax.swing.JFormattedTextField jt_idRepres;
    private javax.swing.JLabel lb_H_extra_entrada;
    private javax.swing.JLabel lb_H_extra_salidad;
    private javax.swing.JLabel lb_entrada;
    private javax.swing.JLabel lb_hora;
    private javax.swing.JLabel lb_horaSALIDAD;
    private javax.swing.JLabel lb_salida;
    private javax.swing.JLabel lt_fecha;
    private javax.swing.JLabel lt_fecha1;
    private javax.swing.JLabel lt_num_Cubiculo;
    private javax.swing.JTextField tx_horaExtra;
    private javax.swing.JTextField tx_horaSALIDAD_extra;
    // End of variables declaration//GEN-END:variables

    public void setCoordinador(Coordinador miCoordinador) {
        this.miCoordinador = miCoordinador;
        
    }

    private void registrar() {
         // VALIDACION DE CAMPOR
        Boolean campos, reglas = null, estudiantes = true;
        String resultado ="", regla = "",a = null;
        // validacionde campos
        campos = Coordinador.ValidarCampos(jt_NomRep.getText(), jt_idRepres.getText());
        // validacionde reglas
         if(cb_1.isSelected() && cb_2.isSelected() &&  cb_3.isSelected() && cb_4.isSelected() && 
            cb_5.isSelected() && cb_6.isSelected() &&  cb_7.isSelected() && cb_8.isSelected() && 
            cb_9.isSelected() && cb_10.isSelected() && cb_11.isSelected() && cb_12.isSelected()){ 
                reglas = true;
            }else if(cb_1.isSelected() || cb_2.isSelected() ||  cb_3.isSelected() || cb_4.isSelected() || 
                    cb_5.isSelected() || cb_6.isSelected() ||   cb_7.isSelected() || cb_8.isSelected() || 
                    cb_9.isSelected() || cb_10.isSelected() ||  cb_11.isSelected() || cb_12.isSelected())
            {
                a ="algun";
                reglas=false;
            }else{
             reglas=false;
                } 
        //validacion de estudiantes
        
        //manejo de ventas
        if(campos && reglas && estudiantes){           
            miCoordinador.ManejoStatus("ok"); 
            miCoordinador.CubiculoStatus(nun_cubico);
        }else{
            if(campos ){ resultado = "*Marcar todas las reglas del Lineamiento \n*Estudiantes(Recuerde que con son Minimos 3 Personas)";}
            if(reglas){ resultado = "*Nombre/Cedula del representante \n*Estudiantes(Recuerde que con son Minimos 3 Personas)";}
            if( a == "algun" && campos ){resultado = "1*Faltan por Marca las reglas del Lineamiento\n*Estudiantes(Recuerde que con son Minimos 3 Personas)";}
            if( a == "algun" && estudiantes && campos==false){resultado = "2*Faltan por Marca las reglas del Lineamiento\n*Nombre/Cedula del representante";}
            if( a == "algun" && estudiantes==false && campos==false){resultado = "3*Faltan por Marca las reglas del Lineamiento\n*Nombre/Cedula del representante \n*Estudiantes(Recuerde que con son Minimos 3 Personas)";}
//            if(estudiantes){ resultado += "Nombre/Cedula del representante y Selecionar todas las reglas del linemiento ";}
//            if ((estudiantes && reglas )){ resultado = "Nombre o Cedula Representante";}
//            if  (campos && estudiantes){ resultado ="Selecionar todas las reglas del linemiento";}
            if  (campos && reglas){ resultado ="Estudiantes(Recuerde que con son Minimos 3 Personas)";}
            if(resultado =="" ){
                JOptionPane.showMessageDialog(null,"El Cubíco no puede ser Prestado. \n Todos Campos Incompletos\n","Error",JOptionPane.ERROR_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null,"El Cubíco no puede ser Prestado. \n Verifique los  Siguientes Campos: \n"+resultado,"Faltan Datos",JOptionPane.WARNING_MESSAGE);
            }
           
        }    
        
   }
   
    public void limpiar(){
        jt_NomRep.setText(null);
        jt_idRepres.setText(null);
        DefaultTableModel modelo = (DefaultTableModel) jt_Cubico.getModel();
        modelo.setRowCount(0);
        
        cb_1.setSelected(false);
        cb_2.setSelected(false);
        cb_3.setSelected(false);
        cb_4.setSelected(false);
        cb_5.setSelected(false);
        cb_6.setSelected(false);
        cb_7.setSelected(false);
        cb_8.setSelected(false);
        cb_9.setSelected(false);
        cb_10.setSelected(false);
        cb_11.setSelected(false);
        cb_12.setSelected(false);
    }
}
